#' @title Interact with INBO LIMS Data
#'
#' @description
#' The `inbolims` package provides a suite of functions to connect to, retrieve,
#' and perform initial processing on data from the INBO Laboratory Information
#' Management System (LIMS) database directly within R.
#'
#' @section Setup and Connection:
#' Before retrieving data, you must establish a connection to the LIMS database
#' using `\code{\link{lims_connect}}`.
#'
#' **Important:** Ensure you have the necessary database
#' credentials and permissions.
#' Refer to the package README for details on setting up credentials.
#'
#' @section Core Workflow Example:
#' This example demonstrates a typical sequence
#' for retrieving and processing data.
#' ```r
#' # Load necessary libraries (ensure inbolims and dependencies are installed)
#' library(tidyverse)
#' library(inbolims)
#' # library(DBI) # Needed for dbDisconnect
#'
#' # 1. Establish connection (requires pre-configured credentials)
#' connection <- lims_connect()
#'
#' # 2. Retrieve report data for a specific project
#' # Replace "I-19W001-02" with your actual project code(s)
#' rapport_data <- read_lims_data(connection = connection,
#'                                project = c("I-19W001-02"),
#'                                sql_template = "default",
#'                                show_query = FALSE)
#'
#' # 3. Process the retrieved data (Examples)
#'
#' #    a. Create a summary overview of samples included in the data
#' staaloverzicht <- lims_report_samples(rapport_data)
#' #    Use View(staaloverzicht) or print(staaloverzicht) interactively
#'
#' #    b. Generate a cross-tabulation (wide format) of the results
#' kruistabel <- lims_report_xtab(rapport_data)
#' #    Use View(kruistabel) or print(kruistabel) interactively
#'
#' # 4. Export processed data or raw data to files
#' #    Example: Export the cross-tabulation to CSV
#' lims_report_export(kruistabel, path = "project_I-19W001-02_xtab.csv")
#'
#' #    Example: Export the raw retrieved data to CSV
#' lims_report_export(rapport_data, path = "project_I-19W001-02_raw.csv")
#'
#' # 5. Disconnect from the database (CRUCIAL!)
#' # Always close the connection when finished to release resources.
#' DBI::dbDisconnect(connection)
#' ```
#'
#' @section Key Functions:
#' The package includes functions for various tasks:
#'
#' **Connection:**
#' * `\code{\link{lims_connect}}`: Establishes the database connection.
#'
#' **Data Retrieval:**
#' * `\code{\link{read_lims_data}}`: Retrieves analysis results data based
#' on project codes or other criteria.
#' * `\code{\link{lims_sample_information}}`: Retrieves detailed metadata
#' about specific samples.
#'
#' **Data Processing & Reporting:**
#' * `\code{\link{lims_report_xtab}}`: Transforms the retrieved data into
#' a cross-tabulated (wide) format, useful for reporting.
#' * `\code{\link{lims_report_samples}}`: Generates a summary table of
#' unique samples present in the retrieved data.
#'
#' **Exporting:**
#' * `\code{\link{lims_report_export}}`: Exports data frames
#' (like those generated by the package or custom ones)
#' to file formats like CSV.
#'
#' @section Important Considerations:
#'
#' - **Credentials & Permissions:** Access to  INBO LIMS database is required.
#' Follow the setup instructions in the README.
#' - **Package Status:** This package is actively developed.
#' While efforts are made for stability, function names, arguments,
#' or behavior might evolve.
#' Check the NEWS file or GitHub repository for recent changes.
#' - **Database Connections:** Remember to explicitly close
#' the database connection using `DBI::dbDisconnect(connection)`
#' when your analysis is complete. Failure to do
#' so can exhaust database resources.
#' - **Dependencies:** Ensure all package dependencies
#' (like `DBI`, `odbc`, `tidyverse`, etc.) are installed.
#' See the DESCRIPTION file or README.
#'
#' @section Further Information and Support:
#' For detailed installation instructions, credential setup,
#' advanced usage patterns,
#' and contribution guidelines,
#' please refer to the package's README file on GitHub:
#' \url{https://github.com/inbo/inbolims/blob/main/README.md}
#'
#' If you encounter issues or have suggestions,
#' please file an issue on the GitHub repository.
#'
#' @seealso
#' `\code{\link{lims_connect}}`, `\code{\link{read_lims_data}}`,
#' `\code{\link{lims_report_xtab}}`, `\code{\link{lims_sample_information}}`
#'
#' @keywords internal
"_PACKAGE"
